export const colors = {
  bg_white: "#FCFDFF",
  bg_black: "#252821",
  text_black: "#252821",
  text_white: "#FCFDFF",
  btn_text: "#252821",
  btn_bg_grey: "#D9D9D9",
  btn_bg_grey_hover: "#BFBFBF",
  switch_yellow: "#FFEE70",
  java_orange: "#FFBB6C",
  go_turq: "#7CEBFF",
  react_mint: "#A4FBF1",
  mysql_blue: "#6DBDFF",
  others_pink: "#FF9A9A",
  ninja_red: "#ee464a",
};
