export const colors = {
  bg_white: "#FCFDFF",
  bg_black: "#252821",
  text_black: "#252821",
  text_white: "#FCFDFF",
  btn_text: "#252821",
  btn_bg_grey: "#D9D9D9",
  btn_bg_grey_hover: "#BFBFBF",
  java: "#FFBB6C",
  go: "#7CEBFF",
  react: "#A4FBF1",
  mysql: "#6DBDFF",
  others: "#FF9A9A",
  ninjaRed: "#ee464a",
};